### ISSUE TITLE
ScrollController not attached to any scroll views

### ISSUE THREAD

**Issue by CodeDoctorDE** [bnxm/sliding_sheet#50]
If I close the sheet, it will throw this error:
```
Error: Assertion failed: 
C:\…\widgets\scroll_controller.dart:112
_positions.isNotEmpty
"ScrollController not attached to any scroll views."
    at Object.throw_ [as throw] (http://localhost:5322/dart_sdk.js:4322:11)
    at Object.assertFailed (http://localhost:5322/dart_sdk.js:4271:15)
    at sheet$._SlidingSheetScrollController.new.get position [as position] (http://localhost:5322/packages/flutter/src/widgets/widget_span.dart.lib.js:28429:59)
    at sheet$._SlidingSheetScrollController.new.get offset [as offset] (http://localhost:5322/packages/flutter/src/widgets/widget_span.dart.lib.js:28434:19)
    at http://localhost:5322/packages/sliding_sheet/src/sheet.dart.lib.js:3795:28
    at _RootZone.run (http://localhost:5322/dart_sdk.js:37060:58)
    at _FutureListener.whenComplete.handleWhenComplete (http://localhost:5322/dart_sdk.js:32068:29)
    at handleWhenCompleteCallback (http://localhost:5322/dart_sdk.js:32565:43)
    at Function._propagateToListeners (http://localhost:5322/dart_sdk.js:32631:15)
    at Function._propagateToListeners (http://localhost:5322/dart_sdk.js:32542:27)
    at _Future.new.[_completeWithValue] (http://localhost:5322/dart_sdk.js:32477:23)

```

My code:
```dart
import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:sliding_sheet/sliding_sheet.dart';

class SettingsPage extends StatefulWidget {
  @override
  _SettingsPageState createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Settings")),
        body: Builder(builder: (BuildContext context) {
          return Container(
            margin: EdgeInsets.symmetric(horizontal: 20, vertical: 10),
            child: ListView(
              children: [
                Card(
                  child: Column(
                    children: [
                      ListTile(
                          title: Text("Theme"),
                          trailing: Icon(MdiIcons.chevronRight),
                          onTap: () async {
                            await showSlidingBottomSheet(
                              context,
                              builder: (context) {
                                return SlidingSheetDialog(
                                    elevation: 8,
                                    cornerRadius: 16,
                                    snapSpec: const SnapSpec(
                                      snap: true,
                                      snappings: [0.4, 0.7, 1.0],
                                      positioning: SnapPositioning
                                          .relativeToAvailableSpace,
                                    ),
                                    builder: (context, state) {
                                      return Material(
                                          child: Container(
                                              child: Column(children: [
                                        ListTile(
                                          title: Text("System"),
                                          leading: Icon(MdiIcons.cogs),
                                          onTap: () {},
                                        ),
                                        ListTile(
                                          title: Text("Light"),
                                          leading: Icon(MdiIcons.weatherSunny),
                                          onTap: () {},
                                        ),
                                        ListTile(
                                          title: Text("Dark"),
                                          leading: Icon(MdiIcons.weatherNight),
                                          onTap: () {},
                                        )
                                      ])));
                                    });
                              },
                            );
                          })
                    ],
                  ),
                )
              ],
            ),
          );
        }));
  }
}
```

**Comment by Dhuliang** [comment]
Same issue

**Comment by kamami** [comment]
I have the exact same issue with the latest version of this package. How was this issue solved?

**Comment by markbulingit** [comment]
Any Update? it's been 3 months now
